language: objective-c
matrix:
  include:
    - osx_image: xcode7.3
    - osx_image: xcode8.2
before_install:
  - rvm install 2.4.0
install:
  - gem install slather
  - bundle install --without=documentation --path ../travis_bundle_dir
script:
  - pod lib lint
  - xcodebuild -scheme 'BMSAnalyticsAPI iOS' clean build CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO
  - xcodebuild -scheme 'BMSAnalyticsAPI watchOS' clean build CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO
  - travis_retry xcodebuild test -scheme 'BMSAnalyticsAPI Tests' -destination 'platform=iOS Simulator,name=iPhone 6s'
  # When merging or pushing to the master branch, release a new version
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && [[ "${TRAVIS_JOB_NUMBER}" = *".2"* ]]; then
      bash scripts/release.sh;
    fi
after_success:
  - slather
